### ISSUE TITLE
Update obsolete Imports!!

### ISSUE THREAD

**Issue by sujaywork** [hashicorp/terraform-website#1023]
Please update the imports from 

"github.com/hashicorp/terraform-plugin-sdk/plugin"
"github.com/hashicorp/terraform-plugin-sdk/terraform"
"github.com/hashicorp/terraform-plugin-sdk/helper/schema"

to
	"github.com/hashicorp/terraform/plugin"
	"github.com/hashicorp/terraform/terraform"
	"github.com/hashicorp/terraform/helper/schema"

Also please fix the documentation to be up-to-date. Please check https://github.com/Mastercard/terraform-provider-restapi for example or any other provider as a reference :)

**Comment by paddycarver** [comment]
The new import paths are correct. `github.com/hashicorp/terraform-plugin-sdk` is the SDK providers should be developing against. Please see https://www.terraform.io/docs/extend/plugin-sdk.html for more information.
