### ISSUE TITLE
Add copy to clipboard buttons

### ISSUE THREAD

**Issue by robbruce** [hashicorp/terraform-website#1043]
It would be very useful if when hovering over resource name and arguments if a _copy to clipboard_ button appeared. I think this would help avoid typo's and speed up the process of IaC development.

**Comment by nfagerlund** [comment]
Web team's been building this for sites on the new platform! Extra details/caveats: 

- terraform.io isn't on the new platform yet, and it'll likely be a couple months still. 
- Current implementation only includes the copy button for commands, not for arbitrary code blocks like in resource docs... but that could change. 
- Provider docs are moving to the registry, so those will need their own solution over there.

**Comment by laurapacilio** [comment]
@jescalan Wanted to check in on this - is this something that will come with the migration once it's completed? If so, I'll close this out :-)

**Comment by jescalan** [comment]
Yes it is!

**Comment by laurapacilio** [comment]
Awesome! @robbruce This should hopefully be available by the end of the year, now that we're migrating. So, we'll work on making sure that all areas that should have them have "copy to clipboard." I'm going to close this out because it's coming soon - thank you for submitting it!
