### ISSUE TITLE
The download for macOS .12.17 is incorrect

### ISSUE THREAD

**Issue by brian-armory** [hashicorp/terraform-website#1044]
The link downloads a file named `terraform_0.12.17_darwin_amd64.zip`, but if you run `terraform --version` this is the output:

```
terraform --version
Terraform v0.12.9

Your version of Terraform is out of date! The latest version
is 0.12.17. You can update by downloading from www.terraform.io/downloads.html
```

**Comment by nfagerlund** [comment]
Hi, I'm not seeing that at all! 

```
╚ᐅ /Users/nick/Downloads/terraform  -version
Terraform v0.12.17
```

You likely have two copies of the binary in your `PATH`; try running `which terraform` and see if it's finding an unexpected copy of it somewhere.
