### ISSUE TITLE
Examples for JSON strings should use jsonencode function

### ISSUE THREAD

**Issue by meustrus** [hashicorp/terraform-website#1047]
Hi!

Since I've started using Terraform recently, I've noticed that most documentation provides the same 1-4 examples for how to include raw JSON in resources:

1. Raw strings in heredoc syntax or double quotes (with escaped double quotes)
2. Separate files with `file()` or `templatefile()` functions
3. Separate files with `template_file` data (no longer recommended since version 0.12, but still recommended in many places)
4. Dedicated data providers for some JSON blocks, such as AWS IAM Policy documents

In this issue I assert that the documentation should include a fifth option and recommend it as the preferred method of creating JSON: the `jsonencode()` function.

#### Escaping

There is one really, really big problem with heredoc and templates files: they don't escape strings. Most of the time, interpolated variables don't need escaping because they don't have backslashes or double quotes.

If they do need escaping, however, they will break the rendered JSON unless they are escaped. In some contexts, the backslashes or quotes need to be *double* escaped, causing further confusion.

Furthermore, if the template variables are provided by user input, there is a possibility for *security* vulnerabilities caused by JSON injection. Granted, Terraform isn't typically a user-facing tool, and I'm not aware of any systems run Terraform with credentials the input provider doesn't have, but in the end, surprises like this often lead developers to create unexpected security vulnerabilities.

#### Formatting and Validation

Heredocs are raw strings. They have no semantic format in Terraform, so the formatter can't fix them.

Template files are a little bit better because they can usually be formatted with JSON formatting tools. However, any interpolation that happens outside of string literals will break these tools.

In addition, because heredocs and template files are raw strings, they are not validated during the plan stage. If there is a JSON syntax error, and misplaced commas happen all the time, there is no feedback until `terraform apply` fails.

#### Poor diff support

Terraform plans don't resolve data. For actual resources, this is a good thing because it means planning doesn't require credentials or generate query costs. For input data, though, this means any changes to the JSON can't be shown in the plan. Plans including JSON from data providers will often show that the existing JSON block is erased and replaced with "known after apply".

#### Unnecessary translation layer

Practically speaking, if you're uploading a JSON document, you're expecting the provider to do something potentially complicated with it. The best documentation will have examples in JSON, not in a Terraform data source.

As a result, data sources which attempt to generate JSON documents in ways more idiomatic to Terraform are and forever will be second-class citizens.

For example, a data source like [aws_iam_policy_document](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html) may be used to generate JSON. But if you want to create a statement with a condition that applies a single operator to multiple keys, the data source will require a separate condition block for each key, while the generated JSON rolls everything for the one operator into a single, concise block.

Even without considering conciseness, however, just assembling one of these documents involves cross-referencing Terraform and AWS documentation, both of which refer to the same things with different names (`test` vs `condition-operator`, `variable` vs `condition-key`, et al). This is a frustrating user experience.

## Why `jsonencode()`?

Since version 0.12, Terraform officially supports JSON syntax. Writing literal JSON inside the `jsonencode()` function fixes *all* of the problems above:

- Data is modeled first in Terraform, then converted to JSON, so there will never be any issues with escaping individual strings or allowing arbitrary JSON injection
- Because the actual JSON is parsed by Terraform and not a raw string, it can be formatted and validated (for syntax) by Terraform itself during the plan stage
- Terraform represents the function call and its argument in the plan, so you don't have to wait for the apply step to see what actually changed in the JSON (except for individual references to data sources or resources
- The document must match the literal requirements from the provider, so there is no need to translate to or from a Terraform-specific configuration style to the actual JSON format when reading documentation

In addition, this strategy allows variables to be referenced directly instead of with interpolation format, making for more readable code and more possibilities for modularity.

## Examples

[The documentation for the `aws_s3_bucket_policy` resource](https://www.terraform.io/docs/providers/aws/r/s3_bucket_policy.html) provides this example:

```
resource "aws_s3_bucket" "b" {
  bucket = "my_tf_test_bucket"
}
resource "aws_s3_bucket_policy" "b" {
  bucket = aws_s3_bucket.b.id
  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "MYBUCKETPOLICY",
  "Statement": [
    {
      "Sid": "IPAllow",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::my_tf_test_bucket/*",
      "Condition": {
         "IpAddress": {"aws:SourceIp": "8.8.8.8/32"}
      }
    }
  ]
}
POLICY
}
```

The JSON could be moved to a separate file and referenced with `file()`, or it could be managed as a [`aws_iam_policy_document`](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html) like so:

```
resource "aws_s3_bucket" "b" {
  bucket = "my_tf_test_bucket"
}
data "aws_iam_policy_document" "example" {
  policy_id = "MYBUCKETPOLICY"
  statement {
    sid       = "IPAllow"
    effect    = "Deny"
    actions   = ["s3:*"]
    resources = ["arn:aws:s3:::my_tf_test_bucket/*"]
    condition {
      test     = "IpAddress"
      variable = "aws:SourceIp"
      values   = ["8.8.8.8/32"]
    }
  }
}

resource "aws_s3_bucket_policy" "b" {
  bucket = aws_s3_bucket.b.id
  policy = data.aws_iam_policy_document.example.json
}
```

I propose that instead, the documentation should recommend this policy document be defined like so:

```
resource "aws_s3_bucket" "b" {
  bucket = "my_tf_test_bucket"
}
resource "aws_s3_bucket_policy" "b" {
  bucket = aws_s3_bucket.b.id
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Id"      : "MYBUCKETPOLICY",
    "Statement" : [
      {
        "Sid"       : "IPAllow",
        "Effect"    : "Deny",
        "Principal" : "*",
        "Action"    : "s3:*",
        "Resource"  : "arn:aws:s3:::my_tf_test_bucket/*",
        "Condition" : {
          "IpAddress" : { "aws:SourceIp" : "8.8.8.8/32" }
        }
      }
    ]
  })
}
```

This document maintains the simplicity and closeness to the actual specification of the heredoc version while *also* gaining the formatting, syntax checking, and interpolation safety of the data source version.

## What documentation?

I'm making this issue here, but I expect that very little in this repository would actually change due to the nature of the web site. It looks like JSON strings are used in at least these places:

- Basic documentation in this repository and the main Terraform repository
- CLI documentation in the [hashicorp/terraform](https://github.com/hashicorp/terraform/) repository
- Provider documentation in the [terraform-providers](https://github.com/terraform-providers/) GitHub organization
- [learn.hashicorp.com/terraform](https://learn.hashicorp.com/terraform), as in [AWS IAM Policy Documents](https://learn.hashicorp.com/terraform/aws/iam-policy) (which may be out of scope here depending on how these pages are managed)
- Various blogs and StackOverflow posts that mimic these original sources of documentation (and which are definitely outside of the scope of this issue)

## How to fix

I feel strongly that this is a good change and am willing to contribute to this project to make it happen. All I really need is buy-in and support. Making the argument here took long enough; I'm not about to go make a giant pull request involving an unknown number of documents without knowing that it's got a good chance of being approved.

There's also an open question, in my mind, as to whether any other method of specifying JSON documents should even be suggested. I think that anywhere that one or two methods are currently suggested, the `jsonencode()` method should replace them as the only example. In some places though, like on learn.hashicorp.com, all the alternatives are provided. It makes sense to document all alternatives *somewhere*, but I think some ideas (especially interpolating unescaped strings into JSON) should not be suggested as much as possible.

This is basically a meta-issue, and I am hoping to attract the attention of somebody with some influence and convince them that `jsonencode()` is the way of the future. If that's you, please reply to this issue and we can get things started.

**Comment by nfagerlund** [comment]
I was withholding judgment on this idea while I mulled it over, but I think I've now come down in favor of it. (I was cleaning up a bunch of single-expression interpolations, and most of the really nasty false-positives were caused by building IAM JSON documents via string interpolation.)

**Comment by meustrus** [comment]
@nfagerlund, thanks for picking this up! I'm glad to see that much of the documentation for the AWS provider uses `jsonencode` now.

I'm sorry I missed it when you replied last year. I'm going to take the opportunity while it lasts and blame it on 2020 being a year. My offer to contribute still stands, although I think you already knocked out the places I knew where to submit a pull request.

**Comment by laurapacilio** [comment]
hi all! It looks like this has been dealt with in the scope of what was suggested in this ticket, so I'm going to close it out. @meustrus Feel free to submit pull requests for any other places you find with this issue and we can review. Thank you both for your work on this (and please reopen if necessary!). :-)
