### ISSUE TITLE
Update code samples to avoid "Interpolation-only expressions" deprecation

### ISSUE THREAD

**Issue by jrr** [hashicorp/terraform-website#1052]
I encountered this in the [batch compute environment example](https://www.terraform.io/docs/providers/aws/r/batch_compute_environment.html#example-usage), but there are likely many of these all over the docs:

```hcl
resource "aws_subnet" "sample" {
  vpc_id     = "${aws_vpc.sample.id}"
  cidr_block = "10.1.1.0/24"
}
```

These should be updated to read:

```hcl
resource "aws_subnet" "sample" {
  vpc_id     = aws_vpc.sample.id
  cidr_block = "10.1.1.0/24"
}
```

Here's the warning you get:

```
Warning: Interpolation-only expressions are deprecated

  on foobar.tf line 166, in resource "aws_subnet" "crab_subnet":
 166:   vpc_id     = "${aws_vpc.crab_vpc.id}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
```

**Comment by nfagerlund** [comment]
It's probably finally an okay time to really sweep all the docs for 0.11-isms.

**Comment by bflad** [comment]
Hi @jrr 👋  Thank you for submitting this awhile ago. We swept the AWS Provider documentation for all Terraform CLI 0.11-isms awhile ago at this point and I believe most, if not all, of other documentation on terraform.io and learn.hashicorp.com has been updated as well. If there are specific cases still around, please reach out via a new issue and thanks again!
