### ISSUE TITLE
Make TF 0.11 requirement for clustering install more visible/informative

### ISSUE THREAD

**Issue by mikegreen** [hashicorp/terraform-website#1056]
Here:
https://www.terraform.io/docs/enterprise/install/cluster-gcp.html#prepare-a-machine-for-terraform
(https://github.com/hashicorp/terraform-website/blob/master/content/source/docs/enterprise/install/cluster-gcp.html.md)

We say `The Terraform module that deploys Terraform Enterprise is written to support Terraform 0.11.x.`

While true, two things I'd like to see improved after seeing some users try with 0.12.x..
- Can we make this red/yellow/more notable
- And, add helpful text for new users to TF that do not know about the 0.11 to 0.12 syntax changes. Something like reiterating "This won't work with TF 0.12.x" because I, like others probably, assumed that it was written for 0.11.x and just hasn't been updated since 0.12 was released

**Comment by glasner** [comment]
@mikegreen good news, these modules will be updated to 0.12 soon so this will no longer be an issue. We'll be sure to note they require 0.12, but it should no longer be such a headache.
