### ISSUE TITLE
google_compute_network example is incorrect

### ISSUE THREAD

**Issue by aaronkrolik** [hashicorp/terraform-website#1087]
The documentation for the [google_compute_network](https://www.terraform.io/docs/providers/google/d/datasource_compute_network.html) includes an incorrect example.

```
data "google_compute_network" "my-network" {
  name = "default-us-east1"
}
```

should be:

```
resource "google_compute_network" "my-network" {
  name = "default-us-east1"
}
```

**Comment by paddycarver** [comment]
That is a data source, not a resource, so the usage there is correct. The resource is here: https://www.terraform.io/docs/providers/google/r/compute_network.html
