### ISSUE TITLE
Upgrade procedure outdated and not clear for current Azure aks design

### ISSUE THREAD

**Issue by porrascarlos802018** [hashicorp/terraform-website#1107]
Please update the document with all the right procedures, step by step guides, limitations , clarifications for skilled and non skilled users in terraform.

Customers are asking for guides and clarifications on how to upgrade aks node pools in multiple pool scenario using vmss and availability set and the correct confirmed process to succeed using terraform. 

The documentation seems to be outdated and missing detailed information with screenshots on how to do it. 

thank you, many users will welcome this improvement.

**Comment by nfagerlund** [comment]
Hi! Thank you for your request, but I'm not quite sure which documents you're referring to, so there's not really anything I can take action on here. If this is still an issue, could you please re-open this ticket and add more information about which documentation needs help? Thanks!
