### ISSUE TITLE
Debugging Terraform page is mildly out of date

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-website#1113]
I believe the information contained in the section on interpreting crash.log files is out of date, as the crashes should be coming from providers not hashicorp/terraform now. I'm also not sure that a crash.log is still written or what's contained in it, so it may be worth just checking that entirely.

Also, it's probably worth adding information on how to hook up delve to the provider binaries or the Terraform binary.

https://www.terraform.io/docs/internals/debugging.html

**Comment by bflad** [comment]
Provider debugging (e.g. via delve) is now present in https://www.terraform.io/docs/extend/debugging.html, however the original issue surrounding the crash documentation is still relevant today.

**Comment by paddycarver** [comment]
Do we want to just drop the crash documentation entirely, as people (realistically) shouldn't be encountering crashes that much in the wild anymore?

**Comment by laurapacilio** [comment]
@bflad just poking on this so we can get it resolved :-)
