### ISSUE TITLE
Update TFE network requirements for clustered install

### ISSUE THREAD

**Issue by sean-nixon** [hashicorp/terraform-website#1125]
I'm currently working on a new TFE clustered install in Azure and have found that the "Network Requirements" section of the documentation does not nearly reflect the actual requirements when running in clustered mode. For example, from my testing I've found the following ports are required but undocumented. There may very well be other that I'm just missing since we still haven't quite gotten a fully functional installation.

- 6443 TCP (kube-apiserver)
- 2379-2380 TCP (etcd)
- 10250-10252 TCP (kubelet and other kubernernetes services)
- 6783 TCP (weave)
- 6783-6784 UDP (weave)
- 5949 TCP (retraced - not positive if this one is required but it's a NodePort service)
- 23432 TCP (timescaledb - same as port 5949 above)

It would be extremely helpful if this documentation could be updated.

**Comment by nfagerlund** [comment]
Yeah, sure enough, [that page](https://www.terraform.io/docs/enterprise/before-installing/network-requirements.html) is outdated. 

I thought I'd seen something more up-to-date go past recently, and I think it must have been [this section on the "custom environment" cluster install page](https://www.terraform.io/docs/enterprise/install/cluster-custom.html#network-configuration). Worth checking up with the TFE team about that; make sure it's current and relevant to all of the environments we support clusters in, and copy it over to the network reqs. page.

**Comment by laurapacilio** [comment]
Hello! Just circling back here. I just spoke with engineering, and we've deprecated support for clustered install since this issue was opened. So, I'm going to close out this PR. But thank you for submitting it - we always appreciate it when folks point out improvements!
