### ISSUE TITLE
Navigation broken on Terraform CLI Command `state`

### ISSUE THREAD

**Issue by calvinsadewa** [hashicorp/terraform-website#1127]
On opening Terraform CLI > Commad > State, Sub navigation only show `state` but not other command

![Peek 2020-02-10 12-08](https://user-images.githubusercontent.com/7587616/74122733-c8bfa280-4bfe-11ea-8d9d-ee128fbcd927.gif)

**Comment by nfagerlund** [comment]
That's by design, and is a longstanding feature of the site... but yeah, I don't really like it either. 

It's likely we'll rethink this, since we're in the process of reworking some of the navs and IA anyhow. I'll leave the ticket open while we consider that.

**Comment by laurapacilio** [comment]
Hi all, 

Going to close this out, as the navigation and information architecture of the site is much different now, and this issue no longer appears to be a problem. Please reopen if that's not the case - thank you!
