### ISSUE TITLE
Please update document

### ISSUE THREAD

**Issue by porrascarlos802018** [hashicorp/terraform-website#1137]
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html

Currently AKS needs to have 2 resource groups for the cluster, the MC_ will hold all the resources created by design. However no other resource should be created in there , because when deleting a cluster it will fail, because a foreign resource was found and to prevent data deletion it wont delete all the contents of the resource group. 

See specific dependencies in regards to this here:
https://docs.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks 
"AKS automatically deletes the node resource whenever the cluster is deleted, so it should only be used for resources which share the cluster's lifecycle."

**Comment by laurapacilio** [comment]
We investigated, and as this has to do with the internals of the Azure Kubernetes Service (which is [documented on Microsoft's website](https://docs.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks)), we're not going to add anything to our documentation on the Terraform Registry. While we want to make sure that our users are successful, the official AKS docs are considered to be the source of truth for the nuances of how the service works.

So, I'm going to close this issue, but we appreciate you bringing this to our attention!
