### ISSUE TITLE
References to partial state in extend should be removed

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-website#1152]
See https://www.terraform.io/docs/extend/writing-custom-providers.html#error-handling-amp-partial-state

Creating this from hashicorp/terraform-plugin-sdk#312

**Comment by bcatubig** [comment]
Hey @paultyng 

I'm new to writing providers and came across this deprecation. 

Is it safe to say that provider authors should not worry about partial state? Is there a better way to handle partial state in providers?  Should partial state not be used at all?

Thanks!

**Comment by paultyng** [comment]
I think the easiest approach is to just ignore this functionality. Core doesn't really have a concept of partial state, this was just a provider/SDK side thing. This is commonly confused with incremental state writing, but its not that its just an SDK behavior.

That being said, what is your use case where you may need some sort of partial state functionality?

**Comment by laurapacilio** [comment]
Closing this since it's been a while and it looks like work related to this issue has since been done. Please reopen if needed - thank you!
