### ISSUE TITLE
Document "operations" attributefor the Workspaces API

### ISSUE THREAD

**Issue by jfpanisset** [hashicorp/terraform-website#1153]
When you create a Workspace on the Terraform Cloud, you can change the setting "Execution Mode" which can be set to:

* **Remote** Your plans and applies occur on Terraform Cloud's infrastructure. You and your team have the ability to review and collaborate on runs within the app.
* **Local** Your plans and applies occur on machines you control. Terraform Cloud is only used to store and synchronize state.

The [documentation for the Workspaces API](https://www.terraform.io/docs/cloud/api/workspaces.html) ([Markdown Source](https://github.com/hashicorp/terraform-website/blob/master/content/source/docs/cloud/api/workspaces.html.md)) does not cover this option, which appears to be controlled by the `operations`  attribute. For instance, the following piece of JSON:

```json
{
  "data": {
    "attributes": {
      "name": "my_test_workspace",
      "operations": false
    },
    "type": "workspaces"
  }
}
```
will create a workspace with the `Execution` mode set to `local`, as reflected in the web UI.

It would be useful if this attribute was reflected in the API documentation, and wherever else it needs to be referenced if not already there (API test suite for instance).

**Comment by nfagerlund** [comment]
Added to API docs in b9694f2c18b070f576738ab841289f493425bb6b
