### ISSUE TITLE
TFE backup/restore document showing inaccurate location of the authentication token 

### ISSUE THREAD

**Issue by hashitop** [hashicorp/terraform-website#1170]
The content of this paragraph in the document stating that the **token** is available under **dashboard** but it is actually located under **Settings** page which could be misleading for some or most people.

https://www.terraform.io/docs/enterprise/admin/backup-restore.html#api-authentication-token

> Calls to the backup API must be authenticated with a special bearer token, which can be found on the install dashboard (https://<TFE HOSTNAME>:8800) near the bottom of the page:

Which should be :

> Calls to the backup API must be authenticated with a special bearer token, which can be found on the **Settings** tab of install dashboard (https://<TFE HOSTNAME>:8800/Settings) near the bottom of the page:

**Comment by sudomateo** [comment]
This was fixed in commit https://github.com/hashicorp/terraform-website/commit/7c19d1c8f62247a4a6970cdd0cfe312405527e13. Closing this issue.
