### ISSUE TITLE
Configuring Azure DevOps Services Access steps 1-2 differed for me

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-website#1213]
RE: https://www.terraform.io/docs/cloud/vcs/azure-devops-services.html

Steps 1 and 2 were different for me. The link to https://aex.dev.azure.com/ took me to a landing page where I saw my ADO orgs. To create a new application I had to go to my organization settings, then on the left under the **Security** subheading select "Authorizations". This  screenshot is where I had to go to register a new app. 
<img width="1392" alt="Screen Shot 2020-04-22 at 7 43 08 AM" src="https://user-images.githubusercontent.com/9982159/79996158-f467d000-846c-11ea-97be-78e89a8c0bdc.png">

**Comment by laurapacilio** [comment]
Hello! Thank you for submitting this! I'm getting the behavior, too, so I'm opening a PR to address it: https://github.com/hashicorp/terraform-website/pull/1846. Just wanted to let you know - thank you for flagging!
