### ISSUE TITLE
Inaccurate API documentation

### ISSUE THREAD

**Issue by Baggerone** [hashicorp/terraform-website#1260]
terraform-website/content/source/docs/cloud/api/workspaces.html.md

says
```page[size]	Optional. If omitted, the endpoint will return 150 workspaces per page.```

but it appears that the default is only `20 workspaces` per page.

**Comment by nfagerlund** [comment]
Yup, sure enough, good catch. Thank you. 

Dealt with this on another page at some point, and it's default 20, max 100. IDEK where 150 came from.
