### ISSUE TITLE
API Documentation Bug - Admin Workspace By Id API

### ISSUE THREAD

**Issue by sjbodzo** [hashicorp/terraform-website#1357]
The description under 'Show A Workspace' is copy-pasted from the list of all workspaces. 

See page [here](https://www.terraform.io/docs/cloud/api/admin/workspaces.html#show-a-workspace).

From the above: 
```
Show a workspace
GET /admin/workspaces/:id

This endpoint lists all workspaces in the Terraform Enterprise installation.
```

**Comment by laurapacilio** [comment]
Hello! Thank you for catching this. This haas not been resolved in [this PR](https://github.com/hashicorp/terraform-website/pull/1811).

**Comment by sjbodzo** [comment]
Thank you @laurapacilio
