### ISSUE TITLE
MongoDB Atlas provider docs taken from archived repo

### ISSUE THREAD

**Issue by languitar** [hashicorp/terraform-website#1381]
The website currently displays the MongoDB Atlas documentation from [this archived repo](https://github.com/terraform-providers/terraform-provider-mongodbatlas) instead of the current correct upstream repo https://github.com/mongodb/terraform-provider-mongodbatlas

**Comment by bflad** [comment]
Hi @languitar 👋  Thank you for raising this.

All of the provider documentation has been migrated to the Terraform Registry, which is based on the source code of a versioned release. The MongoDB Atlas provider documentation can now be found at https://registry.terraform.io/providers/mongodb/mongodbatlas/latest

Please reach out if there are any lingering issues with redirects, etc. Thanks again.
