### ISSUE TITLE
Custom & Community Providers is not compatible with 0.13

### ISSUE THREAD

**Issue by siassaj** [hashicorp/terraform-website#1410]
Specifically the steps to include a custom provider appear not to work with 0.13's provider plugin location structure.

I've contributed to docs before and am happy to submit a PR to update this page but i've no idea which repo to look into to find out where Terraform Cloud wants internal providers to reside and I also don't know who to ask if that source isn't public.

Happy to continue the investigation myself but a point in the right direction would help.

**Comment by mildwonkey** [comment]
(hi @siassaj ! This note isn't *necessarily* for you but feel free to use this info; I stumbled across a page that needs updating and wanted to make sure I wrote down where it is.)
 
I'm sure there are more, but this is one of the pages that needs to be updated: https://www.terraform.io/docs/cloud/run/install-software.html

And it's source is here: https://github.com/hashicorp/terraform-website/blob/master/content/source/docs/cloud/run/install-software.html.md

**Comment by siassaj** [comment]
Found the right way to do it on Cloud, will make a PR.
