### ISSUE TITLE
"extend" provider documentation needs to be updated for terraform v0.13

### ISSUE THREAD

**Issue by mildwonkey** [hashicorp/terraform-website#1412]
Similar to #1410; that issue is terraform cloud specific so I'm opening a new issue but close as a duplicate as needed!

There may be other pages, but [how terraform works](https://github.com/hashicorp/terraform-website/blob/master/content/source/docs/extend/how-terraform-works.html.md) is one of the pages that needs to be updated to include the new (terraform v0.13) plugin installation directory structure, documented [here](https://www.terraform.io/docs/configuration/provider-requirements.html#in-house-providers)

**Comment by bflad** [comment]
Hello, old friend! It feels like its been years already. 😂 

At some point we updated that page to just link to https://www.terraform.io/docs/cli/config/config-file.html#provider-installation, so I believe we have covered this issue! If not, please feel free to reach out in a new issue and we shall take a fresh look. 👍 

Similar to #1470 :shipit:
