### ISSUE TITLE
Incorrect link to PHPIPAM community module

### ISSUE THREAD

**Issue by davemcdonnell** [hashicorp/terraform-website#1418]
Under community -> PHPIPAM the link to the github repo for this module is incorrect (typo).

Its linked to:
https://github.com/lord-kyron/terraform-provider-phpipaim

It should be:
https://github.com/lord-kyron/terraform-provider-phpipam

**Comment by nfagerlund** [comment]
Thanks! Fix submitted in https://github.com/hashicorp/terraform/pull/26047 — I'm going to close this issue now, though, so I don't have to keep track of the status. (I think the "fixes" trick doesn't work cross-repo.)
