### ISSUE TITLE
File name format for upload to https://archivist.terraform.io/ via API

### ISSUE THREAD

**Issue by Hellseher** [hashicorp/terraform-website#1419]
Hi,

Could you update requirements for the file name format in documentation please?
https://www.terraform.io/docs/cloud/run/api.html

Unfortunately it's not clear whether it should be unique or not:

```
UPLOAD_FILE_NAME="./content-$(date +%s).tar.gz"
```

Could I use just constant file name without any random prefix?

```
UPLOAD_FILE_NAME="package.tag.gz"
```

**Comment by nfagerlund** [comment]
If you search the page for that variable name, you'll see that the upload file name is only ever used as an argument to the `curl` command, so it can upload the binary contents of that file. The service that receives that binary content is never aware of the local filename (it only receives the contents as a POST body), so you could use anything. 

Does that satisfy?

**Comment by sudomateo** [comment]
+1 to what Nick said above. The file name doesn't matter to the API. Once you pass the file to `curl`, it will send the content of that file to the API which will generate its own random ID for the configuration version you just uploaded. You could use a static file name and overwrite the file each time if you'd like.

**Comment by bflad** [comment]
@nfagerlund / @sudomateo is there anything else you would like done with this issue?

**Comment by nfagerlund** [comment]
I think let's close it unless anyone else finds this confusing.
