### ISSUE TITLE
Azure DevOps Service Webhook IP Addresses

### ISSUE THREAD

**Issue by straubt1** [hashicorp/terraform-website#1428]
In the page documenting ADO VCS connection, can we add a link to the Microsoft documentation on the originating IP addresses for webhook?

Website Page: https://github.com/hashicorp/terraform-website/blob/master/content/source/docs/cloud/vcs/azure-devops-services.html.md

Microsoft Documentation: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github-enterprise?view=azure-devops#azure-devops-ip-addresses

**Comment by laurapacilio** [comment]
@straubt1 Hi! I can add this, but wanted to see if a) you still think it should be added and b) if so, where on the page you think it would be most effective to mention this for users.  Thank you!

**Comment by straubt1** [comment]
@laurapacilio This page is specific to AzDO to TFC, but my comment is mainly aimed at TFE and an issue a customer had with ip ranges inbound to where TFE was hosted.

I think that each of the VCS connections need clear documentation on the networking requirements for API and `git clone` operations, and those required to make the initial connection. In other words, better describe the two way TLS and DNS traffic required for VCS connections at runtime.

One thought would be to add a Networking Requirements section to each of these pages to more clearly identify these.

**Comment by laurapacilio** [comment]
Okay thank you for clarifying! I'll make an asana ticket for myself to look into this when I've got time :-) For now, this will be on hold as it doesn't seem like it's super pressing and my Q3 is full :-)
