### ISSUE TITLE
Add possibility to switch 'Category' in Settings of Community Provider on registry.terraform.io

### ISSUE THREAD

**Issue by jeremmfr** [hashicorp/terraform-website#1438]
### Use-cases
After publishing a community provider on [registry.terraform.io](https://registry.terraform.io) I can't change `Category` (if I made a bad choice)

### Attempted Solutions
Any

### Proposal
A bouton next to the `Resync` button in `Settings` tab for switch `Category` choice.

### References
I can't switch my provider [jeremm.fr/junos](https://registry.terraform.io/providers/jeremmfr/junos) to `Networking`

**Comment by paultyng** [comment]
This is on our backlog for the registry UI, but if you email terraform-registry@hashicorp.com we can switch this for you.
