### ISSUE TITLE
Initialization of new TFE workspace is required for VCS webhooks to function

### ISSUE THREAD

**Issue by andyKalman** [hashicorp/terraform-website#1454]
I found out through much troubleshooting that a brand new TFE workspace will not respond to VCS webhooks unless it has a prior run that has taken place; even if that run is against no configuration. Granted, the documentation does state so [here](https://www.terraform.io/docs/cloud/workspaces/creating.html#after-creating-a-workspace) in this article and the key excerpt is below:
> A workspace with no runs will not accept new runs via VCS webhook; at least one run must be manually queued to confirm that the workspace is ready for further runs.

The issue is that this is buried deep in the documentation and is almost mentioned as an afterthought. After a few support calls, I was directed to this single but critical sentence. It'd be great to make this a bigger callout and draw more attention to this hard requirement in the article above as well as this article too perhaps for those that are VCS driven:
- https://www.terraform.io/docs/cloud/run/ui.html

Thank you.

**Comment by andyKalman** [comment]
Probably not a bad idea to list it as an answer on your vcs troubleshooting page as well for those that are seeing the behavior of no response to webhooks:
- https://www.terraform.io/docs/cloud/vcs/troubleshooting.html

**Comment by laurapacilio** [comment]
Hello! Thank you for submitting this! I opened a PR to address this issue. It makes the note more salient on the "Creating Workspaces" page, and it also adds a topic to the Troubleshooting guide about this gotcha: https://github.com/hashicorp/terraform-website/pull/1847
