### ISSUE TITLE
Add information about how to use a debugger with a terraform provider

### ISSUE THREAD

**Issue by remyleone** [hashicorp/terraform-website#1474]
On this page: https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#support-for-debuggable-provider-binaries

It is mentioned that it is possible to use a debugger with a terraform provider but I'm not sure about how to do it.
Could you add more explanation about this?

**Comment by bflad** [comment]
Hey @remyleone 👋  Thanks for calling this out. As you later discovered, there is a separate page which includes full details about this topic available here: 

However it would be great if the upgrade guide pointed folks to that page as well. I'll use this issue to ensure that link gets created. Thank you again.
