### ISSUE TITLE
(Google) SEO regression with new site design

### ISSUE THREAD

**Issue by jstrese** [hashicorp/terraform-website#1479]
### Problem
When searching for a resource name in Google we no longer get results that go to the provider specific resource that we searched for.

I'm unsure if this change in results was due to a change on Google or an SEO regression with the new site design. What I do know is that this seems to have started around the time that the new design rolled out.

This **does not affect** every search provider. I've tested DuckDuckGo and Bing and they successfully reference the correct documentation within the first 1-2 results. 

Could this be a SEO regression _specific_ to Google?

### Example
In Google search for "[aws_instance](https://www.google.com/?q=aws_instance)"

### Behavior
The first result goes to the generic resource configuration documentation.

### Expected Behavior
Among the first few results we should see a result linking to the specific resource, [aws_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance)

**Comment by paultyng** [comment]
This does seem to be an issue specific to Google's method of indexing and we are working to resolve it. You can see a previous response here: https://www.reddit.com/r/Terraform/comments/jf5ctt/google_not_indexing_terraform_docs_for_aws/g9jguad?utm_medium=android_app&utm_source=share&context=3
