### ISSUE TITLE
Terraform Datadog provider datadog_monitor and datadog_timeboard docs not found

### ISSUE THREAD

**Issue by amyngyn** [hashicorp/terraform-website#15]
I can't access these pages:
https://www.terraform.io/docs/providers/datadog/r/monitor.html
https://www.terraform.io/docs/providers/datadog/r/timeboard.html

But I can access the other Datadog related pages.

**Comment by grubernaut** [comment]
Hey @amyngyn, thanks for the issue!

Can you still not access the pages, and if so can you possibly paste a screenshot, or any HTTP errors that you're seeing? 

Thanks!

**Comment by amyngyn** [comment]
Yes, I'm still getting 404s.

Here are some screenshots - I'm not sure what information is helpful. Let me know if there's anything else I can provide.

<img width="668" alt="screen shot 2017-08-07 at 1 29 42 pm" src="https://user-images.githubusercontent.com/1736442/29044481-8da02506-7b74-11e7-9726-cfb15a164c91.png">
<img width="1918" alt="screen shot 2017-08-07 at 1 29 31 pm" src="https://user-images.githubusercontent.com/1736442/29044486-911175fa-7b74-11e7-9c0f-3ca9d99d3217.png">

**Comment by grubernaut** [comment]
Hey @amyngyn, 

Looks like our Fastly Cache was invalid due to an internal process error. Mind trying again and verifying you can now hit the affected pages? Thanks!

**Comment by amyngyn** [comment]
Works now (after hard refreshing Chrome)! Thanks for fixing this!
