### ISSUE TITLE
Update Extending Terraform documentation for 0.13 plugin directory structure

### ISSUE THREAD

**Issue by rgl** [hashicorp/terraform-website#1513]
I'm trying to use [nbering/terraform-provider-ansible](https://github.com/nbering/terraform-provider-ansible) by placing it in `~/.terraform.d/plugins/linux_amd64/terraform-provider-ansible`, but `terraform init` never seems to actually find it (**NB** this works fine in 0.12.x). Why is that?

Can 0.13 actually load plugins from local file-system directories (as [described in the documentation](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations))? Or does the plugin need to be in a registry?

Can 0.13 init handle mixed plugins locations? that is, from registry and from local file-system plugin-locations?

Using strace I can see terraform find the `~/.terraform.d/plugins/linux_amd64/terraform-provider-ansible` binary, but it never executes is (at least is does not appear in TG_LOG).

**NB** This is somewhat related to https://github.com/nbering/terraform-provider-ansible/issues/29.

**Comment by taiidani** [comment]
@apparentlymart This is great, thank you very much!

**Comment by paddycarver** [comment]
I've opened #1578 to make the suggested changes raised in this issue.
