### ISSUE TITLE
Request for versioned docs

### ISSUE THREAD

**Issue by eddgrant** [hashicorp/terraform-website#1515]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.8.8

### Affected Resource(s)
Documentation

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
As a user of a specific version of Terraform I should be able to access the documentation relating to that specific Terraform version 

### Actual Behavior
The online documentation seems to only reflect the current latest version

### Steps to Reproduce
1. Open the online documentation e.g.: https://www.terraform.io/docs/providers/index.html
2. Try and find documentation relating to functionality which exists in the specific version of Terraform (which isn't the latest)

### Important Factoids
This is particularly relevant given the recent release of 0.9.0 and the fact that so many people use Terragrunt. Many folks may not be ready to make the switch to 0.9.0 and ditch Terragrunt yet. Getting rid of the 0.8.x docs is problematic as the 0.9.x docs now don't contain any reference to some functions which I presume were removed in 0.9 (for example the commands to manage remote state in <= 0.9.0 versions).

Would it be possible to get the docs versioned? It would probably be a useful thing to have going forward too.

### References
N/A

**Comment by bflad** [comment]
Versioned documentation has also been available for [Terraform CLI](https://developer.hashicorp.com/terraform/cli) and [Terraform Enterprise](https://developer.hashicorp.com/terraform/enterprise) for awhile now (version selector is top right of pages). If there are other specific requests, please raise a new issue.
