### ISSUE TITLE
page title has `env` instead of `workspace`

### ISSUE THREAD

**Issue by johandry** [hashicorp/terraform-website#16]
On page `docs/commands/workspace/select.html` the title is `Command: env select`
I think it should be `Command: workspace select` (`workspace` instead of `env`)
All the other pages for workspace subcommands have `workspace` in the title.

**Comment by RavenAlly** [comment]
hashicorp/terraform pull request #16760 submitted.

**Comment by apparentlymart** [comment]
I just merged hashicorp/terraform#16760, so this should get fixed at the next website deploy, which usually happens as part of a release. Thanks for reporting this @johandry, and sorry for the delay in response!
