### ISSUE TITLE
Module sharing examples show incorrect url path

### ISSUE THREAD

**Issue by johnrothermel-rga** [hashicorp/terraform-website#1607]
The sample request in this link https://www.terraform.io/docs/cloud/api/admin/module-sharing.html has an incorrect api endpoint. 

This `https://tfe.example.com/api/v2/organizations/my-organization` should actually be `https://tfe.example.com/api/v2/admin/organizations/my-organization/module-consumers` based on testing.

**Comment by sudomateo** [comment]
Thank you for reporting this! Submitted #1608 to fix this.
