### ISSUE TITLE
Update broken links in Extending Terraform - Acceptance Testing

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-website#1620]
For example, the terraform-plugin-test library has been replaced by the plugintest package inside the SDK.

https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html

**Comment by judithpatudith** [comment]
👋🏻 Hey @paddycarver and @kmoe! Just want to make sure I'm not dropping the ball on this one. Is your team tracking it or should I take a look?

**Comment by paddycarver** [comment]
I believe we're tracking this, we just haven't been able to devote the time to it just yet. Is it something that needs an immediate remediation or is it OK for us to circle back to it when we can do a more holistic fix?

**Comment by judithpatudith** [comment]
I think it's ok, all the repos have links to the new ones; it just means an extra click. But I don't think anyone is getting hopelessly lost. If I get a sec I'll band-aid it, but a more holistic fix is the right answer for sure.
