### ISSUE TITLE
TFC Agent Limitations confusion

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-website#1654]
Hi folks, this issue pertains to https://www.terraform.io/docs/cloud/agents/index.html#limitations. 

I have a client that interpreted our documentation to mean that tfc-agent was incompatible with a private VCS. As a user of a private VCS, they believed they would not be able to use agents at all. 

I would like to suggest we alter/enhance the wording to make it clear that an agent is compatible with these other configurations if that is indeed the case. 

For example perhaps something like:
### Limitations

Agents are designed to allow you to run Terraform operations from a Terraform Cloud workspace on your private infrastructure. The following use cases are not provided by agents:

- Connecting Terraform Cloud workspaces to private VCS repositories
- Connecting to private infrastructure from Sentinel policies using the [http import](https://docs.hashicorp.com/sentinel/imports/http)

For these use cases, we recommend you leverage the information provided by the [IP Ranges documentation](https://www.terraform.io/docs/cloud/architectural-details/ip-ranges.html) to permit direct communication from the appropriate Terraform Cloud service to your internal infrastructure. Agents are fully compatible with these use cases. 

Organizations are limited to 20 pools each.

**Comment by laurapacilio** [comment]
Hello! I believe this was recently resolved with this PR: https://github.com/hashicorp/terraform-website/pull/1806.  So I'm going to close this out. But please let me know if you have additional comments or suggestions!
