### ISSUE TITLE
Update show workspace API sample response

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-website#1669]
Now that we've added agents and agent pools, it would be good to update the Show Workspaces [sample response](https://www.terraform.io/docs/cloud/api/workspaces.html#sample-response-3). The current response includes agent-pool in relationships.

**Comment by laurapacilio** [comment]
Hi! I put up a little PR to address this, if you'd like to review: https://github.com/hashicorp/terraform-website/pull/1818

**Comment by laurapacilio** [comment]
And now that PR has been merged! So I'm going to close this out. :-)
