### ISSUE TITLE
Fix link rendering on pricing page

### ISSUE THREAD

**Issue by findkim** [hashicorp/terraform-website#1681]
https://www.hashicorp.com/products/terraform/pricing

<img src="https://user-images.githubusercontent.com/6362111/114758332-77d79c80-9d22-11eb-8d40-e549f77ce4ee.png" height=400px>

**Comment by jithenshriyan** [comment]
I'd love to contribute!  I'll take a look at this task, and work on it if no one else is. Thanks!

**Comment by bflad** [comment]
Hi @findkim 👋  It looks like the link issue has been resolved at a certain point since this was opened. Thank you for reporting this and please reach out if you notice anything else!
