### ISSUE TITLE
Dead link in logos page

### ISSUE THREAD

**Issue by xDefcon** [hashicorp/terraform-website#173]
The "Terraform brand guidelines" text in https://www.terraform.io/logos.html links to "https://www.hashicorp.com/brand/terraform/" that outputs a 404 page.

**Comment by bflad** [comment]
Hi @xDefcon! 👋  Thanks for reporting this and sorry you ran into trouble. I have submitted a quick fix pull request for this: #181

**Comment by bflad** [comment]
The fix has been merged into master and will go out next time we release the Terraform website. Thanks!
