### ISSUE TITLE
Dark mode for documentation pages?

### ISSUE THREAD

**Issue by StefanTheWiz** [hashicorp/terraform-website#1746]
It'd be lovely if there was a dark mode for the docs pages
e.g. https://registry.terraform.io/providers/hashicorp/aws/latest/docs

**Comment by laurapacilio** [comment]
Thank you @StefanTheWiz! I am also a fan of dark mode :-)  We're currently working on our docs platform, so I'll pass this along to our web development team. I'm not sure if/when this will be implemented, but I"ll keep it open as a record of the request!

**Comment by sukoneck** [comment]
Seconding this; it would be wonderful. Did it ever make it on to the roadmap?

**Comment by eric-viera** [comment]
yes please, please, I know this is probably way down in the priority list, but as users we would love this!

**Comment by laurenrother** [comment]
Hi folks! Terraform Registry product manager here. I'm way late to replying, but we've noted this request and have it in our backlog. Our backlog is pretty robust at the moment, so I have no sense of when we might get to this, but did want to say we've seen it 😄

**Comment by franciscoprin** [comment]
Any news regarding this? :eyes:

**Comment by michal-mazurkiewicz** [comment]
Haha Yeah I would also love that :D

**Comment by laurapacilio** [comment]
Not yet! But thank you for checking in on it - we know this is a highly requested feature :) But we have several high-priority items on our backlog we're working through first.

**Comment by vazsingh** [comment]
Happy 2023 everyone!
My poor eyes are begging for a dark mode option :-)

**Comment by NIRAVJ96** [comment]
@laurapacilio & @laurenrother do we have any update on this issue? , People is crazy for dark mode.

**Comment by slashbeast** [comment]
Dark mode is not always a matter of preference but for those that are visually impaired it might be much needed accessibility feature. 

I myself am one of those people that needs dark mode because of accessibility. To say that current documentation page that uses light grey text on white background is difficult to work with would be an understatement.

**Comment by sergio-toro** [comment]
would be awesome!

**Comment by rsuplina** [comment]
Guys If you need some folks for Dark UI I got some folks

**Comment by risticmarko** [comment]
how hard can this request be? 
just got back from my eye doc - he told me not to look at terraform docs until there is a dark mode

**Comment by pandeyvinod** [comment]
I agree that working on these type of request which is not directly related to product feature could go down in the backlog. but if we see this as product engagement then it is well deserved request.

**Comment by MiniHeyd** [comment]
As Lauren mentioned above, we are tracking this request in our feature request backlog but it has not made it onto our roadmap yet. We are working to archive this repository and will be closing this issue now. Please reach out to terraform-registry@hashicorp.com with further questions.
