### ISSUE TITLE
On the Remote Service Discovery page, the Internals menu is not expanded

### ISSUE THREAD

**Issue by kconner** [hashicorp/terraform-website#175]
On [Docs > Internals > Remote Service Discovery](https://www.terraform.io/docs/internals/remote-service-discovery.html), the Internals section of the sidebar is not expanded or highlighted. Sibling pages like [Docs > Internals > Debugging Terraform](https://www.terraform.io/docs/internals/debugging.html) do expand and highlight that section.

**Comment by bflad** [comment]
Hi @kconner! 👋  Thanks for reporting this! I have submitted a PR upstream to fix this: https://github.com/hashicorp/terraform/pull/17571

**Comment by bflad** [comment]
The upstream PR has been merged and the updated documentation will be released when Terraform 0.11.4 is released. 🚀
