### ISSUE TITLE
Documentation: Differentiate between data sources and resources better

### ISSUE THREAD

**Issue by craigmonson** [hashicorp/terraform-website#18]
I did a search for something specific relating to aws_vpc. Terraform documentation is very good, so I was able to plop to the page rather quickly. Looking for a specific problem, I scanned down the aws_vpc page (https://www.terraform.io/docs/providers/aws/d/vpc.html), and saw what I was looking for (Attributes). However, I didn't realize I was looking at the page for the _data source_, and not the _resource_. It was confusing, as both are organized very similarly, and there's no big differentiation between them.

I propose adding a simple "Data Source: " before the header to make it more clear:

Data Source: aws_vpc

I think that'd make data sources more visible in the documentation.  I'll be happy to put this together, but I'd rather get a "go for it" before investing some time.

Thanks!

**Comment by RavenAlly** [comment]
terraform-providers/terraform-provider-aws pull request #2422 submitted.

**Comment by craigmonson** [comment]
YAY!  You guys rock!
