### ISSUE TITLE
Getting Started > Resource Dependencies - example S3 bucket name is invalid syntax

### ISSUE THREAD

**Issue by aarongodin** [hashicorp/terraform-website#180]
The code block in the section on implicit and explicit dependencies uses underscores in the example S3 bucket name, but underscores are invalid syntax due to DNS restrictions in the US East Region. See the last paragraph on this page (updated for restrictions going into effect March 1 2018):

https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by bflad** [comment]
Hi @aarongodin! 👋  Thanks so much for reporting this! It certainly looks that way and I have submitted a PR upstream to fix this: https://github.com/hashicorp/terraform/pull/17572

**Comment by bflad** [comment]
The upstream PR has been merged and the updated documentation will be released when Terraform 0.11.4 is released. 🚀
