### ISSUE TITLE
Terraform Plugin SDK/Framework: Add dev_overrides information

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-website#1823]
Currently, the provider development Learn guide advises that learners build the plugin and move it into the appropriate plugin directory: https://learn.hashicorp.com/tutorials/terraform/provider-setup#test-the-provider

This is a good opportunity to introduce users to the `dev_overrides` block, which can be added to Terraform configuration for an easier provider development workflow: https://www.terraform.io/docs/cli/config/config-file.html#development-overrides-for-provider-developers

Recommend updating the Learn guide to use `dev_overrides` instead of manually building and moving the provider binary.

**Comment by laurapacilio** [comment]
Closing this because I recreated it in the learn repo - it's about learn content, so it'll be most useful there!
