### ISSUE TITLE
Claim that Sentinel mocks can only be downloaded for 7 days no longer seems true

### ISSUE THREAD

**Issue by rberlind** [hashicorp/terraform-website#1940]
The claim in https://www.terraform.io/docs/cloud/sentinel/mock.html#mock-data-availability that Sentinel mocks can only be downloaded for 7 days no longer seems true.  I have downloaded mocks that are 3 months old.  I do know that the 7 day limit used to be enforced.  But at some point in the past year, things changed.

What I don't know is whether the doc needs to be updated or whether the TFC engineering team introduced a bug that prevents the 7 day limit (if still desired by them) from being enforced properly.

In any case, this should be investigated.  If the limitation to 7 days was intentionally changed, we need to find out whether it was removed entirely or changed to some longer limit.  If the latter, we need to find out that limit and indicate it in the doc. Otherwise, we should remove mention of the limit.

**Comment by dylanegan** [comment]
@rberlind I believe in the past year, somebody indeed made a change unrelated to mocks that did have an effect on their availability. In this case the documentation could be updated to remove that clause. Do you want to follow up on that or shall I?

**Comment by rberlind** [comment]
Would you mind doing it @dylanegan ?
