### ISSUE TITLE
Azure Active Directory integration update

### ISSUE THREAD

**Issue by JonLyon** [hashicorp/terraform-website#1942]
Could I ask if you can get this article on your website updated. Right now it’s telling your customer to use the Non-Gallery app which isn’t ideal. If we could get this to tell them to get the app from the Azure AD App Gallery that would be great.
https://www.terraform.io/docs/enterprise/saml/identity-provider-configuration-aad.html

**Comment by dylanegan** [comment]
@JonLyon thanks for the report. Please note that we have two implementations for SAML within Terraform Cloud. The link you've shared is for Terraform Enterprise.

https://www.terraform.io/docs/cloud/users-teams-organizations/single-sign-on/azure-ad.html is what we recommend for Terraform Cloud and the SSO integration.

Are you suggesting that for Terraform Enterprise, the gallery application will work without issue too?

**Comment by dylanegan** [comment]
@laurapacilio I'm going to unassign @rexredinger as this is related to Terraform Enterprise.

**Comment by laurapacilio** [comment]
Hello! There is an open PR that I believe will address this issue :) You can track the progress here: https://github.com/hashicorp/terraform-website/pull/1954
