### ISSUE TITLE
API Changelog tag images are oversized

### ISSUE THREAD

**Issue by justinretzolk** [hashicorp/terraform-website#2180]
# Issue

Reading over the [API changelog page](https://www.terraform.io/cloud-docs/api-docs/changelog), I noticed that the images used to tag things as "breaking", "cloud", etc. are rendering out quite strangely. Unfortunately I don't have time to dig into why at the moment, but wanted to open an issue in case someone _does_ have time to look into it.

# Screenshots

<img width="1002" alt="Screen Shot 2022-03-09 at 4 00 20 PM" src="https://user-images.githubusercontent.com/44710313/157543818-2259b97b-123a-47fd-922d-3b0bcba3ec58.png">

<img width="949" alt="Screen Shot 2022-03-09 at 4 02 48 PM" src="https://user-images.githubusercontent.com/44710313/157543906-684abcf4-7892-4ddd-ab17-b522cc93170d.png">

**Comment by laurapacilio** [comment]
@justinretzolk Thanks for flagging this!  I've removed the images from the page entirely and replaced them with bolded text, which I think works well in the context of the changelog (which has very minimal content and formatting for entries). Thoughts?  https://github.com/hashicorp/terraform-website/pull/2300

If you approve, who should we socialize this with to make sure folks know the new way to call out "Deprecations", "Breaking Changes", etc.?
