### ISSUE TITLE
Terraform block provider source documentation hyperlink returning 500 

### ISSUE THREAD

**Issue by ckim328** [hashicorp/terraform-website#2195]
hello!
On this [page](https://learn.hashicorp.com/tutorials/terraform/google-cloud-platform-build?in=terraform/gcp-get-started), under Terraform Block, the hyperlink `To learn more, reference the provider source documentation` returns a 500 error (the link is https://www.terraform.io/docs/language/providers/requirements.html) 
```
This Edge Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: EDGE_FUNCTION_INVOCATION_FAILED
ID: cle1::842sq-1647627909776-e42f883c4f2f
```
I believe it's supposed to be linked to https://www.terraform.io/language/providers/requirements.html 
Thanks!

**Comment by aayushharwani-aidash** [comment]
Hey @ckim328 , It's seems to be working fine. Can you check it once. If everything goes well, can we close this issue ?
