### ISSUE TITLE
Reference-style links don't render correctly if the label includes an underscore

### ISSUE THREAD

**Issue by tlindsay42** [hashicorp/terraform-website#2245]
Just published a couple of modules in the Terraform Registry with all reference-style links in the documentation, and noticed afterward that the links that included an underscore in the label did not render correctly. This is supported in the [Markdown syntax](https://www.markdownguide.org/basic-syntax/#reference-style-links) and all links render correctly locally and in GitHub.

https://registry.terraform.io/modules/aws-ia/content-library/vsphere/0.0.2

![image](https://user-images.githubusercontent.com/11078689/164078481-374fa1b2-301b-4f41-b6cb-b4661478e7b7.png)

https://registry.terraform.io/modules/aws-ia/content-library/vsphere/0.0.2/examples/pub-sub

![image](https://user-images.githubusercontent.com/11078689/164079284-59461f99-d9ee-4309-b1c1-d7f32a60c545.png)

Reference-style links with an underscore in the label should render properly.

**Comment by MiniHeyd** [comment]
We are tracking this issue in our standard pipeline but it has not made it onto our roadmap. We are working to archive this repository and will be closing this issue now. Please reach out to us at terraform-registry@hashicorp.com with any further questions.
