### ISSUE TITLE
Enable copy code snippet in the registry website

### ISSUE THREAD

**Issue by remyleone** [hashicorp/terraform-website#2252]
I'm not sure where to post this. I would like to have on the registry documentation website for a provider: https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/lb_frontend#with-acls the option to copy to my clipboard a snippet of code that is documented. Basically have this code snippet copying feature.

![Capture d’écran 2022-04-21 à 11 30 30](https://user-images.githubusercontent.com/300834/164425321-8b71410f-7a9b-4a3a-b21d-87c139284e76.png)

**Comment by MiniHeyd** [comment]
We have moved this into our standard pipeline but it is not currently on our roadmap. Please reach out to terraform-registry@hashicorp.com with any further questions.
