### ISSUE TITLE
insfrastructure

### ISSUE THREAD

**Issue by amckibben** [hashicorp/terraform-website#2260]
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/2603159/165368355-f7e8de23-64d7-473e-9e5a-282aa9fbb1c9.png">

Typo on the homepage 🙂 Tried to find where the content is coming from to submit an MR against it, but that seems to be private or I'm not smart enough to locate it.

**Comment by mwickett** [comment]
Thanks for raising this @amckibben - that word seems to get us for some reason 😭 

The content here comes from our headless CMS, so we made it really hard for you to find. The typo has been fixed and deployed to production. Thanks again!
