### ISSUE TITLE
Provider webhook is broken: Resync button is missing, referenced in the publishing provider doc

### ISSUE THREAD

**Issue by myoung34** [hashicorp/terraform-website#2329]
[this page](https://github.com/hashicorp/terraform-website/blob/master/content/registry/providers/publishing.mdx) references a `resync` button. Im stuck with a provider that does nto contain this or any settings at all

The webhook (I dont have a SS) showed a bunch of green deliveries but the UI shows nothing.

![](https://aws1.discourse-cdn.com/hashicorp/original/3X/2/a/2aca7475106acb9ae135c12f853f438796718f67.png)

Nothing works here, it only spins. I removed the webhook and it doesnt look like I can get it back via the UI

I added it back manually but now the webhook is a 403 for everything: ![](https://i.imgur.com/B3RcFFE.png)

I then tried to undo it all by removing the github authorization for hashi altogether and logged out/back into the registry. This went back to the github app auth flow just fine, but it wont let me redo any of the import for my provider:

![](https://i.imgur.com/4BHtNol.png)

Going back to that provider I don't have any options to select or logs to see. there's no resync, there's no guidelines on how to get the webhook back, no way to delete the provider, nothing:

![](https://i.imgur.com/hr9GTQR.png)

**Comment by myoung34** [comment]
This seems to be a problem across others with no ideas on resolution: https://stackoverflow.com/questions/71091088/custom-terraform-provider-out-of-sync-on-terraform-registry

**Comment by MartinodF** [comment]
This is still a problem and incredibly frustrating

**Comment by MiniHeyd** [comment]
Please reach out to us at terraform-registry@hashicorp.com for support with publishing issues and we will do our best to assist you. This issue is being closed now as this is not the correct place for support with this kind of issue.
