### ISSUE TITLE
Multiple broken links on the 'Single Sign-on' → 'Linking a User Account page'

### ISSUE THREAD

**Issue by brianearwood** [hashicorp/terraform-website#2340]
All of the links under the **Change SSO Identity Link** and **Remove SSO Identity Link** sections are broken.

---

### Screenshot
<img width="1017" alt="Screen Shot 2022-06-03 at 4 27 15 PM" src="https://user-images.githubusercontent.com/288434/171955543-38573df7-7d9b-44a0-932e-d20c7b1e1561.png">

---

### Error page
<img width="703" alt="image" src="https://user-images.githubusercontent.com/288434/171955600-9ce3d0ef-845a-4308-b89d-657e8ba97721.png">

**Comment by BRKalow** [comment]
These should be fixed now, thanks for the report!
