### ISSUE TITLE
Attribute to enable encryption on EFS(AWS)

### ISSUE THREAD

**Issue by ShwethaThammaiah** [hashicorp/terraform-website#24]
Hello,

AWS now offers encryption on EFS. http://docs.aws.amazon.com/efs/latest/ug/encryption.html
Is there a Terraform attribute that can be used to turn on encryption for an EFS at the time of creation?

Thanks!

**Comment by nfagerlund** [comment]
https://www.terraform.io/docs/providers/aws/r/efs_file_system.html#encrypted
