### ISSUE TITLE
Terraform report

### ISSUE THREAD

**Issue by Pramod6919** [hashicorp/terraform-website#2467]
Hi ,

I am launching different types [t2.micro,t2.medium,etc..] of VM's in AWS with terraform. Can I generate a report after launching my infrastructure. 

I want to know how many machines I've launched  by generating report in text or .md format

Thanks in adavnce!!

**Comment by sudomateo** [comment]
Hello @Pramod6919,

This repository holds content for the Terraform website. Issues within this repository are for the Terraform website only, not Terraform itself.

If you're looking for support for Terraform itself, please refer to the following links:

- https://support.hashicorp.com/
- https://discuss.hashicorp.com/

That being said, Terraform does not support generating a text or markdown report of the infrastructure it manages. You can, however, use the `terraform show` or `terraform show -json` commands to output all the resources that are currently within your Terraform state file in text or JSON format respectively.
