### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by JayadityaGit** [hashicorp/terraform-website#2476]
Hello, I’m a beginner web developer and I really like your website. However, I think it would be great if you could add a dark theme feature for users who prefer a light-on-dark color scheme. This would make your website more accessible and user-friendly.

Would you be interested in adding a dark theme feature to your website? If so, could you please share some resources or tips on how to do it? Thank you for your time and attention.😊

**Comment by bflad** [comment]
Hi @JayadityaGit 👋 Thank you for raising this feature request. There is already an issue tracking this request, #1746, so to consolidate discussions and announcements I'm going to close this issue in preference of the existing one.

Some good news here is that there has been some testing of this functionality internally, so something may be coming soon, but I cannot comment on if/when it will potentially become public.
