### ISSUE TITLE
Clarify Variable Naming Conventions

### ISSUE THREAD

**Issue by bgshacklett** [hashicorp/terraform-website#261]
Hello team. I wasn't sure where to open this, as the content is actually symlinked to the hashicorp/terraform repository, but it's still part of the website. I hope I chose the right place!

The Output Configuration document at https://github.com/hashicorp/terraform/blob/master/website/docs/registry/modules/publish.html.md states (with my added emphasis):
> The NAME given to the output block is the name used to reference the output variable. **It must conform to Terraform variable naming conventions if it is to be used as an input to other modules.**

I'm having difficulty finding the referenced naming conventions, however. It would be great if this might be clarified, perhaps in the Variables document, with the above reference linking to it.

Thanks for your time!

**Comment by nfagerlund** [comment]
Finding this was a bit confusing, but it looks like this was still an issue. PR at https://github.com/hashicorp/terraform/pull/20790; closing this issue bc I can't use the "resolves" shortcut across repos.
