### ISSUE TITLE
add tags to corresponding terraform version

### ISSUE THREAD

**Issue by rolandjohann** [hashicorp/terraform-website#29]
This repo should contain tags that match the terraform versions to be able to generate docsets for specific terraform versions.

**Comment by kkrusedp** [comment]
Seconded.  This would help immensely with managing older versions of tf.

**Comment by laurapacilio** [comment]
Closing because this is a duplicate - https://github.com/hashicorp/terraform-website/issues/1515. But, just know we're still thinking about versioning, and it is hopefully coming soon!
