### ISSUE TITLE
graph -type option does not reflect options provided on CLI

### ISSUE THREAD

**Issue by quixand** [hashicorp/terraform-website#33]
docs https://www.terraform.io/docs/commands/graph.html
shows
-type=plan - Type of graph to output. Can be: plan, plan-destroy, apply, legacy.

CLI output shows
-type=plan     Type of graph to output. Can be: plan, plan-destroy, apply,
                 validate, input, refresh.

**Comment by nfagerlund** [comment]
Sure nuff. I filed https://github.com/hashicorp/terraform/pull/20786. 

Since it's not in this repo I can't use the "resolves ###"  trick, so I'm just gonna close this issue.
