### ISSUE TITLE
Import/export variables

### ISSUE THREAD

**Issue by Nacer-BKRM** [hashicorp/terraform-website#391]
Hi, 

I need some help about terraform API, i want to export my workspace variables and import them in another workspace. 

Actually i'm able to export variables from a workspace , but i'm able to import (through a POST) only one by one. 

Can please tell me what's the syntax to do a POST of all my variables in one curl. 

Thank you in advance for your help.

**Comment by nfagerlund** [comment]
@Nacer-BKRM If you're using the raw API, you just have to do N number of POST requests. There's no multi-variable create endpoint. 

So, I suggest not using the raw API. One of:

- [the tfe cli tool](https://github.com/hashicorp/tfe-cli/)
- [the `tfe` terraform provider](https://www.terraform.io/docs/providers/tfe/index.html)

...will be a much better match for what you want.
