### ISSUE TITLE
Documentation: Add aws_api_gateway_request_validator to documentation

### ISSUE THREAD

**Issue by jerthom** [hashicorp/terraform-website#42]
The `aws_api_gateway_request_validator` resource was added in terraform-providers/terraform-provider-aws#1064 but it isn't listed in the docs as a provider, nor as an argument for `aws_api_gateway_method`.

**Comment by ReallSlimmShady** [comment]
Any update on this?

**Comment by lologhi** [comment]
I've started doing it [here](https://github.com/terraform-providers/terraform-provider-aws/pull/2623).

**Comment by bflad** [comment]
Hi folks 👋 Thanks for reporting this here. We typically track resource specific documentation requests in the provider repositories themselves as that is where the documentation pages live. In this case, I submitted a pull request for the missing documentation here: https://github.com/terraform-providers/terraform-provider-aws/pull/5110
