### ISSUE TITLE
Doc: Provide the resource attributes list that executes state change without resource re-creation

### ISSUE THREAD

**Issue by jayaprakashr88** [hashicorp/terraform-website#44]
Team,

This ticket is created as per the discussion had in https://github.com/terraform-providers/terraform-provider-openstack/issues/137#issuecomment-339670375 

**Issue:**
Incase of any state change to the openstack_compute_instance_v2 resource attributes, Terraform re-creates the instance to apply the change **because of which I lost all my data associated with the instance**.  This might not be same for all the different attributes. 

**Expected change in Documentation:**
Need the list of attributes that executes state change without resource re-creation. 
Atleast I would recommend this for widely used resources like openstack_compute_instance_v2.

**Comment by nfagerlund** [comment]
The https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html page now appears to have this info for all affected arguments. "Changing this resizes the existing server.", "Changing this creates a new server.", etc.
