### ISSUE TITLE
"Edit this page" link is (probably?) broken

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/terraform-website#45]
It's been a while since I last clicked it, so I can't be entirely sure that the behavior has actually changed, but it looks like the "Edit this page link" is broken.

I assume the intended functionality is to open a PR to edit the page being displayed.  Instead, it brings me to the repo's homepage.

**Comment by fordprior** [comment]
Yeah, I'm seeing the same issue. You have to fork then modify and PR, but it would at least make sense for it to at least open to the file location of the page you clicked on.

**Comment by nfagerlund** [comment]
This is now fixed, courtesy of this snippet of helper code https://github.com/hashicorp/terraform-website/blob/master/content/middleman_helpers.rb#L106

**Comment by PatMyron** [comment]
@nfagerlund can this issue be re-opened?

https://www.terraform.io/docs/providers/ is linking to https://github.com/hashicorp/terraform-website

https://github.com/hashicorp/terraform-website/blob/0acf284b67e9a6f2b3225180e9af04abace54666/content/middleman_helpers.rb#L128-L130

**Comment by nfagerlund** [comment]
Ugh! Yeah, looks like you're right. Thanks for pointing it out.
