### ISSUE TITLE
Output variable code does not work properly

### ISSUE THREAD

**Issue by thedini** [hashicorp/terraform-website#455]
## Issue

I encountered an issue when working through the Terraform Quickstart guide

The issue can be found in the following section:

[https://www.terraform.io/intro/getting-started/outputs.html#defining-outputs](https://www.terraform.io/intro/getting-started/outputs.html#defining-outputs)

`output "ip" {
  value = "${aws_eip.ip.public_ip}"
}`

when run the following error occurs:

`Error: output 'ip': unknown resource 'aws_eip.ip' referenced in variable aws_eip.ip.public_ip`

## Workaround
You can use the following code with specifics from the example as a workaround.

`output "ip" {
  value = "${aws_instance.example.public_ip}"
}`

This issue is also documented:
[https://stackoverflow.com/questions/47710135/what-is-wrong-with-this-terraform-code](https://stackoverflow.com/questions/47710135/what-is-wrong-with-this-terraform-code)

**Comment by nfagerlund** [comment]
We believe this has probably been fixed, since these docs have been rewritten several times since! Feel free to re-open if not.
