### ISSUE TITLE
gitlab-eece.html.md has conflicting GitLab API version info

### ISSUE THREAD

**Issue by jacobm3** [hashicorp/terraform-website#636]
Not sure if this is the right place to put this, but the GitLab EE setup instructions specifies conflicting API versions. It says v3 in two places and v4 in one place. Can we please get clarification on what the correct version is? Thanks!

https://github.com/hashicorp/terraform-website/blob/master/content/source/docs/enterprise/vcs/gitlab-eece.html.md

**Comment by armchairlinguist** [comment]
Hey @jacobm3 - I think we got this sorted a little while ago, so I'll close this out, but thanks for the eagle eye!
