### ISSUE TITLE
Writing custom terraform provider missing a requirement

### ISSUE THREAD

**Issue by roccomuscaritolo-okta** [hashicorp/terraform-website#663]
Was looking through https://www.terraform.io/guides/writing-custom-terraform-providers.html#building-the-plugin

The `go build` step was failing with..

```
go build -o terraform-provider-example
```
```
provider.go:4:9: cannot find package "github.com/hashicorp/terraform/helper/schema" in any of:
	/opt/go/src/github.com/hashicorp/terraform/helper/schema (from $GOROOT)
	/home/REDACTED/go/src/github.com/hashicorp/terraform/helper/schema (from $GOPATH)
main.go:4:9: cannot find package "github.com/hashicorp/terraform/plugin" in any of:
	/opt/go/src/github.com/hashicorp/terraform/plugin (from $GOROOT)
	/home/REDACTED/go/src/github.com/hashicorp/terraform/plugin (from $GOPATH)
main.go:5:9: cannot find package "github.com/hashicorp/terraform/terraform" in any of:
	/opt/go/src/github.com/hashicorp/terraform/terraform (from $GOROOT)
	/home/REDACTED/go/src/github.com/hashicorp/terraform/terraform (from $GOPATH)
```

I had to run the following command in order to fix it.
```
go get github.com/hashicorp/terraform
```

This downloaded these files in the default go home dir:
```
~/go/src/github.com/hashicorp/terraform
```

I think we should add this step for `go get` to the docs.

**Comment by dguymon** [comment]
To get the build step working, instead of running `go get` on all of terraform, I just ran the below to get the three specific imports to save time; that also seemed to do the trick:

```
go get github.com/hashicorp/terraform/helper/schema
go get github.com/hashicorp/terraform/plugin
go get github.com/hashicorp/terraform/terraform
```

**Comment by sudomateo** [comment]
Commit https://github.com/hashicorp/terraform-website/commit/6f6b9b5984dbc83fa546814a969858bb45f34f16 updated the documentation to use Go modules instead of relying on the dependencies being located in `GOPATH`. Going to close this issue as a result.
