### ISSUE TITLE
backend s3 documentation

### ISSUE THREAD

**Issue by rednap** [hashicorp/terraform-website#670]
so in your documentation here: https://www.terraform.io/docs/backends/types/s3.html#s3-bucket-permissions

you have bucket permissions for the s3 bucket holding state, but those permission need a "Principal".

it should look more like this:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::############:user/USERNAME"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::MYBUCKET"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::############:user/USERNAME"
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::MYBUCKET/path/to/terraform.tfstate"
        }
    ]
}
```

**Comment by nfagerlund** [comment]
Kinda-sorta! There's two ways to set those permissions, and the example was using the way that attaches directly to a user (and thus doesn't need a `Principal`). PR to clarify at https://github.com/hashicorp/terraform/pull/20791.
