### ISSUE TITLE
Some anchors are incorrect on the glossary

### ISSUE THREAD

**Issue by topfunky** [hashicorp/terraform-website#711]
The glossary has a table of contents at the top that links to anchors on the same page. Some of those links are incorrect. For example, `plan-verb` should link to `plan-verb-`.

Incorrect:

https://www.terraform.io/docs/glossary.html#plan-verb

Correct:

https://www.terraform.io/docs/glossary.html#plan-verb-

Also `plan-noun` should be `plan-noun-`.

**Comment by nfagerlund** [comment]
ah, thx!

**Comment by nfagerlund** [comment]
This is especially annoying because it's one spot where we DON'T follow GitHub's behavior ([Cf.](https://github.com/nfagerlund/evil-made-manifest/blob/master/headerproblems.markdown#ends-with-a-paren)). Bleah.
