### ISSUE TITLE
Search feature on documentation

### ISSUE THREAD

**Issue by cpxPratik** [hashicorp/terraform-website#729]
Is there any chance of search feature on terraform documentation like using Algolia? It can be pretty frustrating hitting doc pages and doing ctrl+F to do quick search something when do not know where to look. Same issue with the documentation of other hashicorp products.

**Comment by mikegreen** [comment]
Would be nice to have, for a workaround, you can search the specific docs with a Google search like:
`site:https://www.terraform.io/docs "ACS consumer"`

**Comment by jcollum** [comment]
I'm really surprised there is no search box anywhere on the site, especially in the docs section. Pretty big oversight.

**Comment by jcollum** [comment]
https://registry.terraform.io/ does have search though, it's helpful

**Comment by laurapacilio** [comment]
Yes, we agree that search would be extremely helpful. I'm closing this because it's a duplicate https://github.com/hashicorp/terraform-website/issues/1516

But know that we're thinking about this, and working on how to add it in.
