### ISSUE TITLE
Link to git repo of each provider

### ISSUE THREAD

**Issue by sixcorners** [hashicorp/terraform-website#800]
It would be nice if there was a link to the git repo of each provider in their documentation.

**Comment by nfagerlund** [comment]
Agreed for sure. 

We're in the middle of an extensive re-think of where provider docs live and how they're presented, and the WIP implementation includes a prominent GitHub link. We're hoping to have that out before the end of the year, so I'm not inclined to add an automatic link feature to the current design.
