### ISSUE TITLE
Add Collapse All to Provider Documentation?

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/terraform-website#801]
Originally posted by @johnwildes in https://github.com/terraform-providers/terraform-provider-azurerm/issues/3511:

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can you add a COLLAPSE ALL to the tree menu on the documentation site.  It's great to have around when looking for something, but difficult to navigate the document if you're just focusing on one resource at a time.

### New or Affected Resource(s)

Resource Provider documentation

**Comment by nfagerlund** [comment]
Heya! The issue with this one is that the sidebar file for the Azurerm provider docs declare that all the sections should default to open. We can change it to be like the AWS sidebar, where sections default to closed and rely on "expand all," individual expand, or search.

**Comment by nfagerlund** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/pull/3605

**Comment by nfagerlund** [comment]
For a variety of reasons, it's not worth the time to integrate a "collapse all" control into the current design.

- In the near term, any provider whose sidebar is unwieldy can remove the `nav-visible` class from its sidebar sections. 
- In the long term, provider docs in the registry will make this a non-issue by defaulting to closed.
