### ISSUE TITLE
Syntax consistency suggestion for getting started documentation

### ISSUE THREAD

**Issue by miqh** [hashicorp/terraform-website#806]
Hello,

I'm new to Terraform and I've been going through the getting started documentation.

I noticed on the ["Input Variables"][1] page that there is mixed usage of first-class expressions and string interpolations. I'm guessing the latter was necessary prior to version 0.12.

Anyway, just thought I'd make a suggestion to amend usages to all be expressions (unless I'm missing something here), seeing as though most of the other pages use this form. I'm happy to make the change, but I can't seem to find where to submit a patch.

https://github.com/hashicorp/terraform/blob/master/website/intro/getting-started/variables.html.md

The above looks like the file I want, but it doesn't exactly match the rendered content seen on the live website, which makes me hesitate about whether that's the right place.

[1]: https://learn.hashicorp.com/terraform/getting-started/variables

**Comment by apparentlymart** [comment]
Thanks for reporting this, @miqh!

As you noticed, the content on learn.hashicorp.com does not originate in the Terraform repository, and the similar files there are vestigial from before the content was migrated to to the new site. The Learn site content is not in an open source repository, so instead we'll pass this feedback into the team that maintains it. Thanks!

**Comment by tr0njavolta** [comment]
Hi @miqh! Thanks for raising this issue. I have updated the private learn repository with 0.12 friendly map variables. 

In the future, we will have a much better way to receive feedback on Learn but for now we will have to tackle issues & requests in this repo.
