### ISSUE TITLE
[Request] Add documentation version corresponding to TF version

### ISSUE THREAD

**Issue by vwordsworth** [hashicorp/terraform-website#808]
I am creating this issue because #29 was neither addressed nor closed. We are running into issues as a result of the unversioned Terraform documentation. Our use-case entails developing tooling to support multiple versions of TF. 

Especially given the major differences between TF 0.12 and older versions, the lack of versioning on the documentation site has already introduced design complications (i.e. seeing documentation about `TF_CLI_CONFIG_FILE` without indication that it is a unique TF 0.12 feature).

It seems as though we are not the only ones facing this issue, as I found an issue in [hashicorp/terraform](https://github.com/hashicorp/terraform/issues/21376) where another user believed they could use this value on Terraform 0.11.

**Comment by svendlarsen** [comment]
Yes please! This would make life so much easier.

**Comment by sshenoys** [comment]
This has caused a lot of confusion trying to adopt terraform .

**Comment by nfagerlund** [comment]
Yeah, I hear you. We want versioned docs too, and we're working on the prerequisites for being able to do that, but it's gonna be a little while yet.

**Comment by laurapacilio** [comment]
Closing because this is a duplicate (of a few others, too - this is a very highly requested feature!).  https://github.com/hashicorp/terraform-website/issues/1515

But just know we're still thinking about this, and it's hopefully coming soon!
