### ISSUE TITLE
https://www.terraform.io/docs/enterprise/vcs/bitbucket-server.html needs to be updated to latest Bitbucket Version

### ISSUE THREAD

**Issue by scarolan** [hashicorp/terraform-website#826]
Some of the dialog options have been moved, this page should be updated to reflect the latest version of Bitbucket and the required plugin.

**Comment by nfagerlund** [comment]
I think we brought this up-to-date in July, with a few extra updates since, so I'm going to close this issue for now. Feel free to reopen or start a new issue if there's other outdated stuff you want to point out!
