### ISSUE TITLE
Typo in vsphere virtual machine firmware property documentation

### ISSUE THREAD

**Issue by amarruedo** [hashicorp/terraform-website#83]
There is a typo in the documentation, following `annotation` element:

[https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#annotation](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#annotation)

`firmware` property is not correctly html formatted.

**Comment by vancluever** [comment]
Hey @amarruedo - this was caught yesterday by @jason-azze - it was fixed in terraform-providers/terraform-provider-vsphere#313 and will be updated next release!

Thanks for pointing it out!
