### ISSUE TITLE
Values of InstanceIDs should be a list 

### ISSUE THREAD

**Issue by gitackt** [hashicorp/terraform-website#866]
## Summary
https://www.terraform.io/docs/providers/aws/r/ssm_association.html

in `aws_ssm_association` document example usage, 

```
resource "aws_ssm_association" "example" {
  name = "${aws_ssm_document.example.name}"

  targets {
    key    = "InstanceIds"
    values = "${aws_instance.example.id}"
  }
}
```

shoud be 

```
resource "aws_ssm_association" "example" {
  name = "${aws_ssm_document.example.name}"

  targets {
    key    = "InstanceIds"
    values = ["${aws_instance.example.id}"]
  }
}
```

**Comment by ryndaniels** [comment]
Hi @gitackt - thanks for bringing this to our attention! I've got a PR going to fix this [here](https://github.com/terraform-providers/terraform-provider-aws/pull/9604). In the future, if you have other provider-specific documentation issues, opening those in the provider repo (in this case, the [terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws/) repo) would help us out a lot keeping things organized! 👍 Thanks!
