### ISSUE TITLE
Fix wrong naming scheme for third-party provider plugins

### ISSUE THREAD

**Issue by ilyasotkov** [hashicorp/terraform-website#91]
<https://www.terraform.io/docs/configuration/providers.html#third-party-plugins>

> The naming scheme for provider plugins is terraform-provider-NAME-vX.Y.Z, and Terraform uses the name to understand the name and version of a particular provider binary.

The actual naming scheme is "terraform-provider-NAME_vX.Y.Z" with an underscore before the version tag, not a dash.

**Comment by RichieRunner** [comment]
Why was this closed? I thought that IS a valid scheme.

**Comment by ilyasotkov** [comment]
I closed this because it was quitely fixed.

> The naming scheme for provider plugins is terraform-provider-NAME_vX.Y.Z, and Terraform uses the name to understand the name and version of a particular provider binary. Third-party plugins will often be distributed with an appropriate filename already set in the distribution archive so that it can be extracted directly into the plugin directory described above.

**Comment by dferretti-fig** [comment]
@ilyasotkov what is the purpose of the -x3 and _x4 I see in the docs and in the providers?
https://www.terraform.io/guides/running-terraform-in-automation.html shows `terraform-provider-aws-v1.0.0-x3` and the file inside https://releases.hashicorp.com/terraform-provider-aws/1.13.0/terraform-provider-aws_1.13.0_linux_amd64.zip for example is named `terraform-provider-aws_v1.13.0_x4` 

Does that mean the version is v1.13.0_x4 or does the _x4 mean something else?
If I create my own custom provider, do I need to name it `terraform-provider-myprovider_v1.0.0_x4` as well?

**Comment by dferretti-fig** [comment]
If anyone else is looking, got an answer here https://groups.google.com/forum/#!topic/terraform-tool/EolJNDaPqw8
