### ISSUE TITLE
Typo at https://www.terraform.io/docs/providers/do/r/ssh_key.html

### ISSUE THREAD

**Issue by discentem** [hashicorp/terraform-website#92]
Current state:
> Provides a DigitalOcean SSH key resource to _allow you manage SSH keys_ for Droplet access. Keys created with this resource can be referenced in your droplet configuration via their ID or fingerprint.

Potential correction:
> Provides a DigitalOcean SSH key resource to allow you **to** manage SSH keys for Droplet access. Keys created with this resource can be referenced in your droplet configuration via their ID or fingerprint.

I would have correct this typo myself but I can't find the GitHub repo where this particular page is housed.

**Comment by tombuildsstuff** [comment]
hey @discentem 

Thanks for opening this issue!

Unfortunately the Terraform Website's spread over multiple repositories at the moment (and thus is fairly complex to discover unfortunately). The Documentation for each Provider is contained within the Repository for each Provider and then imported into this repository as a Git Submodule (against the `stable-website` branch - which in this case would be in the [Digital Ocean Provider](https://github.com/terraform-providers/terraform-provider-digitalocean) - where I've opened PR terraform-providers/terraform-provider-digitalocean#61 which contains this suggestion :)

As such I'm going to close this issue in favour of the PR terraform-providers/terraform-provider-digitalocean#61 which should solve this :)

Thanks!
