### ISSUE TITLE
REST API Java client for terraform

### ISSUE THREAD

**Issue by roopahc** [hashicorp/terraform-website#931]
Hello,
 Is there any rest API client written in java supporting terraform enterprise? It would be very helpful to use it in the CI-CD pipeline with other java components. Please let me know if there is any plan to support this feature. 
This library could be a wrapper on HTTP client handling connection pool and a bunch of POJOs to set and get API parameters.
Please let me know what do you think about this.

**Comment by nfagerlund** [comment]
We don't have any plans to write an in-house Java client for our API. Sorry! 

- If someone develops one and contacts us about it, we'll gladly add a link to our [list of known client libraries.](https://www.terraform.io/docs/cloud/api/index.html#client-libraries-and-tools)
- If you'd like to develop one yourself, the other client libraries might provide a good starting point, especially the official [go-tfe](https://github.com/hashicorp/go-tfe) client. 
- If you just need to integrate Terraform runs into CI/CD and don't need deeper integrations with Terraform Cloud/Enterprise's data, you might want to try using the remote backend and having CI run the normal `terraform plan` / `terraform apply` commands.
