### ISSUE TITLE
Report a broken link on TFE Cloud Best Practice

### ISSUE THREAD

**Issue by hashitop** [hashicorp/terraform-website#949]
The link [Terraform Up and Running: Writing Infrastructure as Code](https://www.amazon.com/Terraform-Running-Writing-Infrastructure-Code-ebook/dp/B06XKHGJHP/ref=sr_1_1?ie=UTF8&qid=1496138592&sr=8-1&keywords=terraform+up+and+running) under [Part 3.2/Section 4. Share Knowledge](https://www.terraform.io/docs/cloud/guides/recommended-practices/part3.2.html#4-share-knowledge) seems to be now broken.

The book is probably no longer available on amazon website as far as I can search.

**Comment by nfagerlund** [comment]
Good catch, thank you.
