### ISSUE TITLE
Github actions/ deprecated actions

### ISSUE THREAD

**Issue by canelkatmis** [hashicorp/terraform-website#984]
Afaik actions/bin/filter actions is deprecated and tags argument can be used instead of that
terraform-website/content/source/docs/github-actions/running-apply.html.md

**Comment by nfagerlund** [comment]
Thanks for reporting! We've got someone working on code changes that should fix this, but it'll take a little more time, since it needs to fit in around some other responsibilities.

**Comment by nfagerlund** [comment]
I think this is now fixed! Please feel free to re-open if that's not the case. 👍🏼
